### ISSUE TITLE
Composer problem

### ISSUE THREAD

**Issue by sprit-pl** [synatree/yii2-dynamic-relations#1]
psikora@SPRITNB1:~/Projects/sprit$ composer require --prefer-dist synatree/yii2-dynamic-relations "*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package synatree/yii2-dynamic-relations could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by synatree** [comment]
Try taking out --prefer-dist and adding "dev-master" instead of "*"

**Comment by synatree** [comment]
I updated the documentation to remove the "*" and replace it with "dev-master", and remove the prefer-dist flag.  I also added a screenshot of the component working if you are interested.
