### ISSUE TITLE
js loading before jquery?

### ISSUE THREAD

**Issue by tiffoknee** [synatree/yii2-dynamic-relations#2]
Hi, 

I can't work out why it's doing it, but I am having a problem with dynamic relations' js loading before jquery - and of course it's throwing jquery is not defined problems...

```
<script src="/assets/bf2ab30f/js/dynamic-relations.js"></script>
<script src="/assets/94aa2f1e/jquery.js"></script>
<script src="/assets/afbd7acd/yii.js"></script>
<script src="/assets/f35b37a4/js/bootstrap.js"></script></body>
```

Am I missing something mad obvious here?

**Comment by tiffoknee** [comment]
I seem to have fixed this by adding in a dependancy to SynatreeAsset:

```

    public $depends = [
        'backend\assets\AppAsset',

    ];
```

but it's not elegant

**Comment by synatree** [comment]
I think I can add JQueryAsset to the dependencies to take care of this.  Thanks for the heads up, for some reason this wasn't happening to me.
