### ISSUE TITLE
using standard activeform..

### ISSUE THREAD

**Issue by tiffoknee** [synatree/yii2-dynamic-relations#3]
I may be being a bit simple, but I can't work out how to use just a simple input field or dropdown in the inline section, can you bung in a demo? Apologies if overtiredness is causing problems, it's a very handy bit of thing you have here and I want to use it!

**Comment by tiffoknee** [comment]
Ah, I see what the problem is (with other bits) - this is only designed to work with the basic app. I am too sleep deprived to work out how to extend it right now, but I will see about sorting it tomorrow

**Comment by synatree** [comment]
I've never yet had occasion to deal with the "advanced" app layout; let me know if this gets resolved and I'll add it to the documentation.  Otherwise, maybe there is something I can generalize in path handling or something.  I'll add some examples with standard widgets too.

**Comment by sblaut** [comment]
I made a pull request that addresses the problems regarding the advanced app layout.
