### ISSUE TITLE
Using DynamicRelations with Select2

### ISSUE THREAD

**Issue by Bilalkh** [synatree/yii2-dynamic-relations#4]
I'm trying to use this widget to create multiple records. Each record includes nested Select2 widgets.

What's weird is that if there is data already the Select2 widgets are loaded perfectly.

If there is no data, upon clicking on "Add", the Select2 widgets are not loaded properly, seems like their CSS is not loading properly.

Is there a solution for this?

**UPDATE**
I fixed the issue by register the assets in the parent view (Select2Asset::register($this))

**Comment by synatree** [comment]
Sorry, I didn't see the notification for this issue.  I'm glad you solved it!
