### ISSUE TITLE
500 (Internal Server Error)

### ISSUE THREAD

**Issue by jb-studio** [synatree/yii2-dynamic-relations#6]
Hi!
For some reason I do have this error message when I click Add button
/dynamicrelations/load/template?hash=884798551&t=1443591601291 500 (Internal Server Error)
Can you please point me what is wrong?

**Comment by jb-studio** [comment]
I am using "advanced" version

**Comment by synatree** [comment]
Turn on the Yii2 debugger plugin, it will give you the exact line where the problem is.
