### ISSUE TITLE
How should I define the collection?

### ISSUE THREAD

**Issue by AntoninSlejska** [synatree/yii2-dynamic-relations#7]
I receive the following error message:
"Getting unknown property: frontend\models\Parent::relatedRecords"

I do not know how to define the collection in frontened/views/parent/_form.php:

```
<?= DynamicRelations::widget([
    'title' => 'Related records',
    'collection' => $model->relatedRecords,
    'viewPath' => '@app/views/related-record/_inline.php',
    'collectionType' => new \appnep\models\RelatedRecord,
]); ?>
```

I'm also not quite sure, what should I write in RelatedRecordController.php in actionCreate and actionUpdate:

```
DynamicRelations::relate($model, 'parent', Yii::$app->request->post(), 'RelatedRecord', RelatedRecord::className());
//           Parent Model --^       ^-- Attribute      ^-- Array to search    ^-- Root Key    ^-- Model Class Name
```

What should I use as Attribute and Root Key?

**Comment by synatree** [comment]
The collection and collectionType are your related model, for example if you wanted to add children to a parent record, app\models\Child would be your collectionType and $model->children would be your collection. "relatedRecords" should be replaced with your model's hasMany relation.
